const hamburger=document.querySelector(".hamburger");const navMenu=document.querySelector(".nav-menu");const navLink=document.querySelectorAll(".nav-link");hamburger.addEventListener("click",mobileMenu);navLink.forEach(n=>n.addEventListener("click",closeMenu));function mobileMenu(){hamburger.classList.toggle("active");navMenu.classList.toggle("active");}
function closeMenu(){hamburger.classList.remove("active");navMenu.classList.remove("active");}
function analyze(){if(document.getElementById('closeCaptchaModal'))
document.getElementById('closeCaptchaModal').click();let $downloadForm=$('#downloadForm');if($downloadForm[0].checkValidity()){$("#loader-area").css('display','flex');$("#result").css('display','none');$downloadForm.submit();}}
function checkCaptcha(event){event.preventDefault();let link=$('#link').val();let referer=$('#referer').val();analyze();}
function getUrl(){let privateLink=$("#privateLink").val();let referer=$("#referer").val();let locale=$("#locale").val();if(privateLink.trim()==="")
return false;$.ajax({type:"get",url:"/get-url",data:{privateLink:privateLink,referer:referer,locale:locale,},beforeSend:function(){$("#loader-area").css('display','flex');$("#result").html('');$("#alertArea").html('');$("#response").val('');},success:function(data){$("#loader-area").css('display','none');if(data.url!==undefined){window.open(data.url);}else{$("#privateLink").val('');$("#alertArea").html(data);let myModal=new bootstrap.Modal(document.getElementById('errorModal'));myModal.show();}}});}
let errorModal=document.getElementById('errorModal');if(errorModal!==null){new bootstrap.Modal(errorModal).show();}
$("#link").keypress(function(e){if(e.which==13){e.preventDefault();checkCaptcha(e);}});$("#response").keypress(function(e){if(e.which==13){e.preventDefault();analyze();}});$("#privateLink").keypress(function(e){if(e.which==13){e.preventDefault();getUrl();}});$("#privateLink").bind('paste',function(){setTimeout(function(){getUrl();},200);});$('.image-link').magnificPopup({type:'image',gallery:{enabled:true}});currentPos=$(window).scrollTop();resultPos=$("#result").offset();if((typeof resultPos!=="undefined")&&(currentPos<resultPos.top)){$('html, body').animate({scrollTop:resultPos.top},1000);}
$(window).on('load',function(){$('#loader-area').hide();});if('serviceWorker'in navigator){navigator.serviceWorker.register('/serviceworker.js',{scope:'.'}).then(function(registration){console.log('ServiceWorker registration successful');},function(err){console.log('ServiceWorker registration failed: ',err);});}